### ISSUE TITLE
Look at continuous testing through Travis as a way to validate contributions

### ISSUE THREAD

**Issue by krook** [Project-Owl/owl#11]

**Comment by yhwang** [comment]
@krook and @knouse1344 I can work on this. My thought is that we can start on travis and it's free for open source project in github. And in order to do the set up I need the permission to change the repo settings.

**Comment by knouse1344** [comment]
how can we get you permissions?  Happy to do that.

**Comment by knouse1344** [comment]
@yhwang I've added you as an admin to the repo.

**Comment by yhwang** [comment]
yes, I accepted the invitation and will start to work on the settings! Thanks.

**Comment by krook** [comment]
@yhwang Let me know if you have any questions. I've got a few of my repos configured already, like https://github.com/IBM/ibm-cloud-functions-serverless-iot-openfridge

**Comment by yhwang** [comment]
@krook thanks and I also enabled Travis CI for some repos. However, I think the key things here are the permission. When I set up Travis CI for my own repos, I don't have issue with the permission(since I own the repo/org). The repo you mentioned above belongs to IBM org. Anything you need to do in order to have it show up in your Travis?

**Comment by yhwang** [comment]
@knouse1344 can you accept my request to join the `Project-Owl` org?

**Comment by knouse1344** [comment]
Couldn't find an invite, but I believe I just added you.  please let me know if I did not do it correctly.

**Comment by knouse1344** [comment]
awesome.  yeah, for whatever reason i had no notification, but i think we're good now.

**Comment by yhwang** [comment]
@knouse1344 Just sent a travis-ci integration request to `@Project-Owl` account. Please accept it and I can create a PR to verify the travis-ci integration.
