### ISSUE TITLE
Create a separate ClusterDuck repo for the hardware portion of Owl

### ISSUE THREAD

**Issue by krook** [Project-Owl/owl#13]
Doesn't need to happen right away. We discussed also having a separate `web` repo along with `cyberduck` and `owl` repos. May be a good thing to discuss the pros and cons of.

**Comment by hawk4031** [comment]
I am in full agreement of this. This way, we don't pollute any of the pieces with code that belongs somewhere else.

**Comment by krook** [comment]
@knouse1344 and I chatted about this on the phone yesterday. We should aim to implement this sooner rather than later, because it will make it clearer as to where a developer might start contributing to the project as the community ramps up this month. It's also easer to do this refactoring while there's less project activity.

The way I see it, these would be the steps:

1. Move the `owl/Hardware - ClusterDuck` folder into its own new repo as just `clusterduck` (or `duck`). The README in that subdirectory looks pretty good as a standalone top-level entry point.
2. Disentangle the Ruby on Rails files for the general web site (project-owl.com) and the OWL dashboard itself. This could start by cloning the `owl` repo, removing its `.git` directory, creating a new `web` repo, then changing the remote origin and pushing. Here are some possible approaches to 
"mirroring" though really what we are doing is creating two completely separate repos.
https://help.github.com/articles/duplicating-a-repository/
https://gist.github.com/niksumeiko/8972566#gistcomment-1696452
3. Strip the web-related controllers, models, and views from the old `owl` repo.
4. Strip the OWL-related controllers, models, and views from the new `web` repo.
5. Update the respective READMEs as needed.

@hawk4031 what are your thoughts on this? Do you want to propose a more detailed plan and run with it?

**Comment by krook** [comment]
Also created a new `api` repo.

**Comment by krook** [comment]
Looks like @hawk4031 was able to copy the ClusterDuck stuff into its own `duck` repo, but it still needs to be removed from the main `owl` repo. @nfeuer @Atlantice do you want to take that on since you're leading the hardware side? See my comment above about a possible strategy.

**Comment by krook** [comment]
Done!
