### ISSUE TITLE
Get a free Let's Encrypt SSL certificate for project-owl.com

### ISSUE THREAD

**Issue by krook** [Project-Owl/owl#17]
Also happens to be a Linux Foundation project.

https://letsencrypt.org/

**Comment by hawk4031** [comment]
I was actually looking into this last week but haven’t implemented just yet. 

Charlie Evans

**Comment by krook** [comment]
Cool. What made me notice it is that my ISP now "helpfully" injects a header banner into non-HTTPS web sites. Sigh.

<img width="1915" alt="optimum-browser-hijacking" src="https://user-images.githubusercontent.com/1499840/50048356-e98e7580-0097-11e9-9c56-480e15f3b01f.png">

**Comment by knouse1344** [comment]
not to mention ads?  What browser is this?

**Comment by krook** [comment]
It's just Chrome. As soon as I saw it called Optimum and gave them an earful. They now think it's OK to add an additional payload to HTTP sites in order to deliver me updates about my own account.

**Comment by krook** [comment]
Looks like there are some steps here to explore: https://drissamri.be/blog/2017/02/22/lets-encrypt-cloudfoundry-bluemix/

**Comment by DanCunnington** [comment]
We'll also likely need to use the same certificate for secure MQTT messaging to/from Watson IoT. I've used lets encrypt before for my department website, certificates normally expire after 90 days so it would be good to automate the renewal process. 

It's possible to POST a new certificate in Watson IoT which would help with the automation: https://docs.internetofthings.ibmcloud.com/apis/swagger/v0002/security.html#!/Authentication_-_CA_Certificates/createAuthenticationCertificate

**Comment by hawk4031** [comment]
This has been implemented finally!
